[package]
name = "greek-meander"
version = "0.1.2"
edition = "2024"
description = "A Rust crate for creating rectangle border design of Greek Key (Meander)."
license = "MIT"
repository = "https://github.com/bingqiao/meander"
keywords = ["greek-key", "meander", "svg", "rectangle"]
categories = ["multimedia::images"]

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
resvg = "0.45.1"
svg = "0.18.0"
